name: End-to-end tests
on: [push, pull_request]

jobs:
  cypress-run:
    runs-on: ubuntu-22.04

    steps:
      # Step 1: Check out the repository
      - name: Checkout
        uses: actions/checkout@v3

      # Step 2: Set up Node.js environment and install dependencies
      - name: Install dependencies
        run: npm install
        working-directory: frontend_next

      # Step 3: Build the Next.js application
      - name: Build application
        run: npm run build
        working-directory: frontend_next

      # Step 4: Start the server
      - name: Start server
        run: |
          npm start &
          echo "Waiting for server to start..."
          sleep 15  # Wait for 15 seconds to give the server time to start
        working-directory: frontend_next

      # Step 5: Wait for the server to be ready
      - name: Wait for server to be ready
        run: |
          echo "Waiting for server to be ready..."
          until curl -sSf http://localhost:3000 > /dev/null; do
            echo "Server is not ready yet..."
            sleep 5
          done
        working-directory: frontend_next

      # Step 6: Run Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          working-directory: frontend_next
